### ISSUE TITLE
插件使用图片时排版和显示不正确

### ISSUE THREAD

**Issue by carolcoral** [halo-sigs/plugin-hybrid-edit-block#3]
## Version
* halo: 2.10.2
* plugin: 1.0.1

## Description
1. 新建文章
2. 选择`默认编辑器`
3. 选择`MMarkdown编辑块`
4. 在块中新增一下两个图片内容，期望是并排显示，但是实际上换行显示，其次显示的样式和实际样式也存在差异

```markdown
# 检测网站并自动重启OpenResty服务

![Static Badge](https://img.shields.io/badge/1Panel-v1.8.3-green?style=flat&logoColor=yellow&label=1Panel&labelColor=blue&color=green&cacheSeconds=3600&link=https%3A%2F%2F1panel.cn%2F)

![Static Badge](https://img.shields.io/badge/OpenResty-1.21.4.3-blue?style=flat&logoColor=yellow&label=OpenResty&labelColor=blue&color=green&cacheSeconds=3600&link=https%3A%2F%2F1panel.cn%2F)

```

* 图示1
<img width="486" alt="image" src="https://github.com/halo-sigs/plugin-hybrid-edit-block/assets/8952687/855792a2-0397-423c-a38e-7cdc1373bcd2">

* 图示2
<img width="1004" alt="image" src="https://github.com/halo-sigs/plugin-hybrid-edit-block/assets/8952687/ee01519e-4635-4415-bd6e-63a20443d7aa">

* 图示3
<img width="147" alt="image" src="https://github.com/halo-sigs/plugin-hybrid-edit-block/assets/8952687/489d9cdd-2efd-4d94-9d46-14c25612d2fe">

**Comment by carolcoral** [comment]
## 补充
使用HTML标签语法会导致内容变形


<img width="1020" alt="image" src="https://github.com/halo-sigs/plugin-hybrid-edit-block/assets/8952687/aa493420-104a-4aa1-b3c4-be8754974816">
<img width="721" alt="image" src="https://github.com/halo-sigs/plugin-hybrid-edit-block/assets/8952687/af531e97-80d4-438e-9301-3bbcfe1412bd">

**Comment by LIlGG** [comment]
markdown 中使用 `![]()` 语法是不能并排显示两个的，此插件也并不支持 `![]() ![]()` 这种写法，因此需要使用到 html 才可以。
例如如下语法：

```markdown
<figure style="display: flex; justify-content: space-around">

![Static Badge](https://img.shields.io/badge/1Panel-v1.8.3-green?style=flat&logoColor=yellow&label=1Panel&labelColor=blue&color=green&cacheSeconds=3600&link=https%3A%2F%2F1panel.cn%2F)

![Static Badge](https://img.shields.io/badge/OpenResty-1.21.4.3-blue?style=flat&logoColor=yellow&label=OpenResty&labelColor=blue&color=green&cacheSeconds=3600&link=https%3A%2F%2F1panel.cn%2F)

</figure>
```

或者另一种方法是使用 markdown 的 table 语法，也可以做到，就不赘述了。

但似乎目前 markdown 编辑器无法二次渲染 HTML 内容。这个倒是一个新问题，我会重开一个 issue。
