### ISSUE TITLE
markdown内容块Task list保存后方括号被清除

### ISSUE THREAD

**Issue by Litbay** [halo-sigs/plugin-hybrid-edit-block#6]
### 环境
Halo 2.11.0；Markdown / HTML 内容块插件 1.0.1

### 问题描述
使用默认编辑器插入markdown代码块后，书写Task list，如图所示
[![piXRNAf.md.png](https://s11.ax1x.com/2024/01/01/piXRNAf.md.png)](https://imgse.com/i/piXRNAf)
保存并发布文档后，再次打开编辑文档，方括号会被清除掉，Task list就会变为无序列表了，如图所示
[![piXRUN8.md.png](https://s11.ax1x.com/2024/01/01/piXRUN8.md.png)](https://imgse.com/i/piXRUN8)

**Comment by LIlGG** [comment]
任务列表是 GFM 扩展的一部分，目前 markdown 编辑块在回显时还没有支持 GFM 相关扩展，可以考虑支持。

/kind feature
