### ISSUE TITLE
分栏卡片里插入代码块，气泡被遮挡

### ISSUE THREAD

**Issue by Litbay** [halo-sigs/plugin-hybrid-edit-block#7]
本插件版本1.0.1
在默认编辑器的分栏卡片里插入markdown代码块，markdown的编辑气泡弹窗会被分栏卡片的气泡遮挡
如图所示：
[![piXRgEV.md.png](https://s11.ax1x.com/2024/01/01/piXRgEV.md.png)](https://imgse.com/i/piXRgEV)

**Comment by LIlGG** [comment]
这是默认编辑器的冒泡菜单 BUG。
